# Generated by Django 5.0 on 2024-02-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogx',
            fields=[
                ('blog_id', models.IntegerField(primary_key=True, serialize=False)),
                ('blog_name', models.CharField(max_length=100)),
                ('blog_code', models.CharField(max_length=1000)),
                ('blog_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
