# Generated by Django 5.0 on 2024-02-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogx',
            name='blog_desc',
            field=models.CharField(max_length=1000),
        ),
    ]
