# Generated by Django 5.0 on 2024-02-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appx', '0003_alter_blogx_blog_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogx',
            name='blog_code',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='blogx',
            name='blog_desc',
            field=models.TextField(max_length=5000),
        ),
    ]
