# Generated by Django 5.0 on 2024-02-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appx', '0004_alter_blogx_blog_code_alter_blogx_blog_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogx',
            name='blog_code',
            field=models.TextField(max_length=5000),
        ),
    ]
