# Generated by Django 5.0 on 2024-02-01 12:23

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appx', '0005_alter_blogx_blog_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogx',
            name='slugx',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='blog_name', unique=True),
        ),
    ]
