# Generated by Django 5.0 on 2024-02-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appx', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='cum',
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
