# Generated by Django 5.0 on 2024-02-01 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appx', '0010_alter_comment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='timestamp',
        ),
    ]
